# Using the node alpine image to build the React app
image: node:10.16.0

# Announce the URL as per CRA docs
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration
variables:
  PUBLIC_URL: /ReactWithGitLab
# Cache node modules - speeds up future builds
cache:
  paths:
  - node_modules

# Name the stages involved in the pipeline
stages:
- build
- test

build:
  stage: build
  script:
    - npm run build --prod # Build for prod

  artifacts:
    paths:
    - dist # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch